- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/Assets.xcassets/AppIcon.appiconset/Contents.json
- NewDawn/NewDawn/Base.lproj/LaunchScreen.storyboard
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/Info.plist
- NewDawn/NewDawn/ProfileViewController.swift
- NewDawn/NewDawn/RegisterUserViewController.swift
- NewDawn/NewDawn/SignInViewController.swift
- NewDawn/NewDawn/ViewController.swift
- NewDawn/NewDawnTests/Info.plist
- NewDawn/NewDawnTests/NewDawnTests.swift
- NewDawn/NewDawnUITests/Info.plist
- NewDawn/NewDawnUITests/NewDawnUITests.swift
> App basics & SignIn/Register/Profile skeleton

- NewDawn/NewDawn/Info.plist
- NewDawn/NewDawn/RegisterUserViewController.swift
Hopefully we can use this as a sample to send POST registration request to server.
@tianchuxie Let me know what do you think about it.
> A simple and temporary Request sample

- NewDawn/NewDawn/RegisterUserViewController.swift
- NewDawn/NewDawn/SignInViewController.swift
Enable login with some basic validity check.
Successful login and register will bring the user to profile page.
Will also get access token from backend.
Otherwise alert message will be displayed.
Change auto-generated username to email since it is more unique
Also refactor common used code into a library applied to all UI views.
Test e2e:
> Enable Login with real username and password

- NewDawn/NewDawn.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/ProfileViewController.swift
- NewDawn/NewDawn/SignInViewController.swift
Request Profile Info through GET API & Display for login user
Sign-out implementation
Also memorize the username and accesstoken. If the user has already login, he doesn't need to login again unless sign out
Test:
Verified that sign out can lead user to login page
> Request Profile Info through GET API & Implement Signout

- README.md
Update readme to include install dependency
> Update readme to include install dependency

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/PhoneAuthenticateViewController.swift
- NewDawn/NewDawn/PhoneVerifyViewController.swift
This is a test for phone verification request on iOS
Use two test pages since the UI pages are not available yet.
Test e2e:
> Test Phone Verification on iOS

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/ViewController.swift
- NewDawn/Pods/Pods.xcodeproj/project.pbxproj
@tianchuxie Let me know if this looks good to you. Can it automatically resolve the version inconsistency between my code and yours?
If so, I think you can run the same command in that repo so you don't need to manually update anything I guess?
> Run Edit/Convert/To Current Swift Syntax

- NewDawn/NewDawn/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileGNBViewController.swift
- NewDawn/NewDawn/ViewController.swift
1. Put some code in shared viewer controller for simplicity.
2. Add button selection library and used in women/men selection.
3. Add date picker for birthday field
4. Store all data in local storage after clicking continue
> Add button selection UI + date picker

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_DrinkSmoke.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
- NewDawn/NewDawn/ViewController.swift
"Unselect buttons" func can help with single choice page scenario, where you cannot have multiple choice.
Video can be view in slack
> Add UI for Smoke View + Unselect buttons func

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNBViewController.swift
Modify Name field to Firstname field and Lastname field. Make them stored locally and read the default value when the view is loaded
Video in slack
> Record Gender/Firstname/Lastname/Birthday in local storage during registration

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
> Store smoke page info to local storage

- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
#42 
Handle nil value for smoke pref.
> debug optional

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_Education.swift
- NewDawn/NewDawnTests/NewDawnTests.swift
Had to comment out the testable thing since it keeps throwing target deployment error.
> Add empty choice to education dropdown

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/QuestionAnswer.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/QuestionAnswerViewController/AnswerQuestionViewController.swift
- NewDawn/NewDawn/QuestionAnswerViewController/QuestionViewController.swift
- NewDawn/NewDawn/QuestionAnswerViewController/SelectQuestionViewController.swift
- NewDawn/NewDawn/ViewController.swift
1. Add a navigation view to all QA views.
2. Auto-generate questions and display in a scroll view
3. Make question selectable and be able to slide to answer page with the selected question.
Videos in slack
> [QA][2/n] Question Navigation + Slide to answer page.

- NewDawn/NewDawn/Base.lproj/QuestionAnswer.storyboard
- NewDawn/NewDawn/QuestionAnswerViewController/QuestionViewController.swift
Support removing Answered Questions from UI.
Video in slack
> [QA][4/N] Support Answered Question Removal

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNBViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Drink.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Education.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
- NewDawn/NewDawn/ProfileViewController/Profile_HomeTown.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
- NewDawn/NewDawn/ProfileViewController/Profile_WorkJob.swift
- NewDawn/NewDawn/ViewController.swift
#53 
- End to end registration testing
- Modified previous continue button segues
- Local storage key for workplace to employer
- extension += to merge dicts
> Register to backend (Except Image/Video)

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
#61 
- Proof of concept using smoke page
- Name segue with identifier.
- shouldPerformSegue and performSegue logic.
> Activate alert message

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
added skip button, "continue" on photo page;
add an overlay to choose the image from the gallery;
able to resize it as the square.
> photos tested need future work

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/MainPageViewController.swift
- NewDawn/NewDawn/SettingPageViewController/SettingPageViewController.swift
1. Add navigation title for all tabs
2. Hide back button for main page
3. Add view controller file for each view
> Add Navigation Title and View Controller for tab pages

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/SettingPageViewController/SettingPageViewController.swift
- NewDawn/NewDawn/ViewController.swift
> Setting UI init

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
The button reference was broken. Add this fix.
> [fix] Multi page action button link

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_HomeTown.swift
#59 
- Fix hometown registration page
- rename hometownTextField
- Add registration reference in Setting -> Setting to easier operate.
Video in slack.
> [Fix]Hometown

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/MainPageViewController.swift
- NewDawn/NewDawn/MainPageViewController/MainPageEndViewController.swift
- NewDawn/NewDawn/ProfileIndexUtil.swift
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/TimerUtil.swift
- NewDawn/NewDawn/ViewController.swift
Add an end main page. Add some timer utils to refresh main page.
Currently the refresh is always true so we can circular view the main page. In the future it will comply to the date.
> Add an end main page. Add some timer utils to refresh main page.

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNBViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Smoke.swift
#78 
According to user story
Alert required fields:
Firstname, lastname, gender, DOB, height.
Optional:
All else to be UNKNOWN if not inputted.
> Alert required fields and secure optional fields

- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/TimerUtil.swift
> Make timer not always outdated

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/MainPageViewController.swift
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/ProfileIndexUtil.swift
- NewDawn/NewDawn/ViewController.swift
1. Add modal popups for like action. Display liked contents.
2. Add comment function and the ability to adjust the frame when keyboard appears. The keyboard also have a "Done" button.
3. Add helper function to ProfileIndexUtil.
> [Main Page] Like Button Action + Like Popup + Comments features

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/Models/UserModels.swift
> [Main Page] Add title to the popup window and fix some typos in the past

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/QuestionAnswer.storyboard
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewController.swift
Setup development env
Fix some bugs including
1. Constraints on some views
2. Keyboard has no Done button
3. Change server request
Next step is to verify Main Page
> FIX Registration Keyboard Input and Constraints

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/MainPageViewController.swift
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/QuestionAnswerViewController/AnswerQuestionViewController.swift
1. Add missing fields and cleanup image/question answer fetch.
2. Change QUESTION_ANSWERS string to make it consistent with backend.
3. Minor changes to only allow the first image to show Name, age, job.
4. Add a sorting function
5. Minor change to getURL to make sure we align with the url format returned from backend
> E2E Main Page Profile Fetch Request with Testing Users automatically created in backend

- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/Models/UserModels.swift
#98 
- End to end send action request
- Added account_id and entity_id for user action
- Set default numeric value for Enum
Video can be found in slack.
> End to end like action(Image and Question)

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/ChatUtil/ChatUtil.swift
- NewDawn/NewDawn/ImageUtil/ImageUtil.swift
- NewDawn/NewDawn/SettingPageViewController/SettingPageViewController.swift
- NewDawn/NewDawn/ViewController.swift
> [ChatPage] Chat Page Table View

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileSettingViewController.swift
#70 
- Table view for switch action
- Privacy & sign out button
- Initialize pop-out window
> [1/N] Profile Setting Initiation

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileSettingViewController.swift
- Account switch
- Notification switch to setting
- Log out alert
- Privacy Statement
Video can be found in Slack.
> [2/N]Setting page UI reactions

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/ProfileViewController/ImageCollectionViewCell.swift
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
#52 
- CollectionView formatting
- Image from gallery/ camera
- Delete Button
Video can be found in Slack
> Images upload with CollectionView 

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
- LongPressingGesture will trigger Drag and Drop
- Control state of LongPressingGesture
- indexPath changes according to start and destination spot
Video can be found in slack.
> Drag and drop photos by LongPressingGesture

- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
#52 
- Reformat photosUpload with extensions.
- Continue tapped to save images to "PersonalImages" in disk.
- Handle jpeg and png formats.
Video can be found in slack.
> Save Image to Document Directory

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/Models/UserModels.swift
Enable realtime delivery and message backend sync. Tested on two devices.
> [Chat] Sync messages from backend. Real-time Delivery E2E.

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileSettingViewController.swift
> [Easy] Setting page back button to TabBarView

- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
#113, #112 
Delay image upload after register.
> [Image Upload/Registration] Test Registration + Image retrieval

- NewDawn/NewDawn/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ProfileViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Education.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
- NewDawn/NewDawn/ProfileViewController/Profile_HomeTown.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Photos.swift
- NewDawn/NewDawn/ProfileViewController/Profile_WorkJob.swift
- NewDawn/NewDawn/RegisterUserViewController.swift
- NewDawn/NewDawn/SignInViewController.swift
- NewDawn/NewDawn/ViewController.swift
#116 
- Async session task register -> image upload
- Delete/ Format register code files.
- Commented out unused session task, that will be adjusted.
Register E2E tested.
> Async session task + real user id + hashed img name

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
> Fix setting navigation

- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/SettingPageViewController/SettingPageViewController.swift
Profile page image default to be the first chosen image.
> Setting image and pesudo user to real user

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
> Retrieve last messages from each chat

- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/ViewController.swift
getURL functiion
get login user id
> Some Debug for E2E test

- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
Image will be loaded only once.
Notice that NSCache is ephemeral cache
Video in slack
> [Optimization] Cache downloaded images (url -> UIImage)

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
> [Bug fix] Question Answer Word Wrapping with Adjustable Text Height

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
Profile image constraint
Real phone test.
> profile image constraint

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/ImageUtil/ImageUtil.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
#80 
PNG to JPEG photos while uploading, and compress them between a range by adjusting the alpha channel.
Video can be found in slack.
> Binary image compression

- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
> More height options

- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/ImageUtil/ImageUtil.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/ViewController.swift
1. Fetch profile info in chat room page so profile image can be displayed as avatar
2. Slight refactor of user profile builder to make it more adaptable to other use cases (main page, chat page, and hopefully setting preview page)
3. Add download image helper function to conveniently download UIImage
4. Unify getURL function in different places
> [Chat] Chat Message Avatar

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/MainPageViewController/MainPageTableViewCell.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/ViewController.swift
If the user liked you, it will show as a banner. 
The message is currrently missing since it is not sent from front-end yet.
> [Main Page] Show liked banner in main page for people liked you

- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
- NewDawn/NewDawn/ImageUtil/ImageUtil.swift
- NewDawn/NewDawn/Models/Message.swift
> [Chat] Like Message at the top of Chat

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatProfileViewController.swift
- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
> [Chat] Go from user avatar to its chat profile

- NewDawn/NewDawn.xcodeproj/xcshareddata/xcschemes/NewDawn.xcscheme
- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/SettingPageViewController/SettingPageViewController.swift
- setting page png to jpeg
- random username password
Video in Slack
> Update info when existing user registers

- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/ModalPopupViewController.swift
- NewDawn/NewDawn/PhoneAuthenticateViewController.swift
- NewDawn/NewDawn/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ProfileSettingViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- NewDawn/NewDawn/ViewController.swift
1. Registration is now back with phone verification and authentication.
2. Login using existing phone number is not supported yet (will be follow-up)
3. If user typein "testomni" in phone number field, it will login as a super user. This is for debug only.
4. User can logout and jump back to phone number verification page. All local stored stuff will be wiped out.
> [Login] Bring Registration Back as the first page

- NewDawn/NewDawn/PhoneAuthenticateViewController.swift
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
> [Login] If phone number already registered, jump to main page

- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
> Test Like QuestionAnswer

- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/MainPageViewController/MainPageTabBarViewController.swift
Client will check matched users every time switching tabs and unseen matched id will trigger notification.
Video in Slack.
> In app notification after match

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNBViewController.swift
1. Keyboard not enough space in Work/Job info page
2. Done/Cancel button flip
> [fix] Two keyboard minor fix

- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_PhotosUpload.swift
> Enforece at least 3 images

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/AppDelegate.swift
- NewDawn/NewDawn/AppLandingViewController.swift
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/MainPageViewController/MainPageViewModels.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/QuestionAnswerViewController/AnswerQuestionViewController.swift
1. Add a landing page to handle async profile fetching
2. Remove forced unwrap of user profile
3. Add id field to liked image and question answer items sending to backend
> Landing page + fix ID of liked items

- NewDawn/NewDawn/ProfileViewController/Profile_Education.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
> [easy] Align Done button to the right in pickers

- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/PhoneAuthenticateViewController.swift
> [login] Popup Options for Phone Number Re-verify

- NewDawn/NewDawn/ProfileViewController/Profile_Education.swift
- NewDawn/NewDawn/ProfileViewController/Profile_Height.swift
> [Easy] Height limit and education default

- NewDawn/NewDawn/AppLandingViewController.swift
- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/PhoneAuthenticateViewController.swift
> [chat] Fix my avatar in chat room. Segue to my own profile when tapped + Full name displayed

- NewDawn/NewDawn/ChatPageViewController/ChatRoomViewController.swift
> [easy] fix chat profile

- NewDawn/NewDawn/LocalStorageUtil.swift
- NewDawn/NewDawn/QuestionAnswerViewController/SelectQuestionViewController.swift
> [QA] Remove answered questions

- NewDawn/NewDawn/HttpUtil/HttpUtil.swift
- NewDawn/NewDawn/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
- Perform segue after register
- Change testomni
Video can be found in Slack.
> To main page only after successful register

- NewDawn/NewDawn/ChatPageViewController/ChatPageViewController.swift
> [chat] Do not show icon if message is sent by the login user himself

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNB.storyboard
- NewDawn/NewDawn/ProfileViewController/ProfileGNBViewController.swift
- Setting profile image overlap on 8 and X
- "How tall are you"
- Delete skip continue in image upload
- Constraint in image upload
- Hide navigation bar in slack video
> A list of UI adjustments

- NewDawn/NewDawn/ProfileViewController/Profile_DraftFinal.swift
> [Easy] Activity indicator when sending register request

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
> [Fix] Unable to display "people who matches with you" on iPhone X

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/PreferenceSonViewControler.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/PreferenceViewController.swift
(Table View)Preference Intro Page init
Gender preference page with click buttons
Video in Slack
> Preference Page and gender selection

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
1. Click my photo to segue to my profile
2. Get profile image from login user's userProfile instead of local directory
video in slack
> [Settings] Click my photo to go to my profile + retrieve profile image from my login user profile instead of local folder

- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTableViewCell.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
1. Fix the profile segue prepare in settings page. Since there are more then one segue from that page, the destination is not necessary go to profile (can be preference too).
2. Put main image load below shadow layer
> [Easy] fix segue + main page image display after shadow

- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneVerifyViewController.swift
> Phone verifying UI new

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_HomeTown.swift
Rearranged the page to match the new design.
Modified the style of the button, the text field and labels
Took out the "Previous" button and the "Invisible" function from the storyboard and swift code
> Changed the Hometown UI to the new design (issue #184)

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
Debug constraint misplace for iphone X.
> Profile GNB constraint

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Height.swift
1. Implement the back button;
2. Add "公分".
> Back button in Height UI

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_WorkJob.swift
New UI design for Work and Job page.
> New work UI

- NewDawn/NewDawn/Models/Message.swift
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
Overwrite some MessageKit functions or attributes
> [Chat] New bubble color and font

- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_DraftFinal.swift
Since the new birthday page is updated with yyyy-mm-dd format, the _birthday_str_handler function in draft_final is no longer valid.
> [BUG] Fix wrong birthday format + add registration failure alarm when server return error msg

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Models/LikeInfo.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/Utils/LikeInfoUtil.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTableViewCell.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewModels.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/ModalPopupViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/RectInfoViewController.swift
1. Draw Like Me popup modal UI with Question Answer first
2. Refactor like info dicts into models. Add likeInfoUtil to fetch like info the user sends or receives
3. Update popup model with like info and images of two users.
> [Like] New LikeMe UI + Refactor of Like model

- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/Utils/HttpUtil.swift
- NewDawn/NewDawn/Utils/LocalStorageUtil.swift
- NewDawn/NewDawn/ViewControllers/AppLandingViewController.swift
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatPageViewController.swift
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneAuthenticateViewController.swift
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTabBarViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTableViewCell.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/RectInfoViewController.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_DraftFinal.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
- NewDawn/NewDawn/ViewControllers/ViewController.swift
> [Error Handling] All Http request is required to pass the error message into callback so view controller can throw them out

- NewDawn/NewDawn/Utils/HttpUtil.swift
Both 200 and 201 should be deem as successful
> [EASY] minor fix the response check

- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/ModalPopupViewController.swift
Should use user id instead of user name
> [Easy] Fix like action

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Smoke.swift
> New UI for smoke page

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/RectInfoViewController.swift
Added the modal view for liked photos and updated some details for liked question&answer
> new liked photo view

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Notificatioin.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/ProfileSettingViewController.swift
> [Registration] Last pages

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Drink.swift
> [Registration] New Drink UI

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/Utils/LocalStorageUtil.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Drink.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
> [Setting] Setting texts and buttons

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
> [Preview] click eye to preview

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/CustomLayouts/VerificationTextField.swift
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneAuthenticateViewController.swift
1. Change the overall UI for the phone verification page;
2. Add a new subclass of UITextfield for the new verification text field;
3. Screen recording is uploaded to Slack.
> New UI For Phone Verification Text Field

- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneAuthenticateViewController.swift
Add "再寄出一组验证码“ to the pop up in phone verification page.
> Phone verification page new pop up

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/ProfileGNBViewController.swift
> Minimum 18 age in date picker

- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/Utils/ImageUtil.swift
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewModels.swift
The viewer can see the image/qa they send to the end user.
> [Chat] Display like info from viewer to end user

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ImageCollectionViewCell.swift
- NewDawn/NewDawn/CustomLayouts/ImageCollectionViewCell.xib
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
By using nib file, make custom cell with layout generalized enough to be reused in edit profile page.
> Refactor image upload using nib file

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/ProfileGNBViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
- Constraints of continue button
- Remove Help and Feedback
> [Setting] Constraints and remove

- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/PreferenceSonViewControler.swift
> [Setting] Store preference value locally

- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
Logic to allow image to swap in local storage.
Video in Slack.
> [Image Upload] Swap Image Positions in Local Storage

- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/ProfileGNBViewController.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
> [Registration] No videos in image picker

- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewModels.swift
Add REQUEST_TAKEN to the chatroom I'm taken AlertController.
> [I'm Taken][3/n] Send REQUEST_TAKEN from iOS to backend

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewModels.swift
> Unmatch in Chat Page

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
Encapsulate image uploading logic to model
EditProfile can use it as an element
E2E tested
> [Edit Profile] Refactor Image controller to image model

- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
1. Add "专属邀请已成功寄出” alert after clicking corfirm button;
2. The alert will automatically diminish;
3. The screen recording is uploaded to Slack.
> I'm Taken pop up

- NewDawn/NewDawn/Utils/HttpUtil.swift
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewModels.swift
1. add "ACCEPT_TAKEN" action;
2. when user accept taken, admin console will receive the action;
3. an alert will display after user accept.
> [I’m Taken][7/n] Add “ACCEPT_TAKEN” action

- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
Also fix a bug after upgrading to MessageKit 3.0
Video in slack
> [Chat] Scroll to last message when keyboard appears

- NewDawn/NewDawn/Utils/ProfileIndexUtil.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTabBarViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewController.swift
> [Main Page] Add a counter bubble on top of main page tab bar

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/CustomLayouts/VerificationTextField.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Education.swift
> [Fix] Done button on keyboard +3 dots segue was removed + degree in mandarin

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- Overwrite local profile editing stored info
- Alert when empty fields
- Sync with Back End after back
Video in slack
> [Edit Profile] Edit profile GNB subview

- NewDawn/NewDawn/Base.lproj/Main.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
make sure all buttons have same constraint across profile GNB
> [Fix] fix button constraint on registration page

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Height.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_HomeTown.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Location.swift
> [Registration] Change home town info page to location info page

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
Subview Controllers of Edit Profile and their UIs.
Video in slack.
> [Edit Profile] Work + Edu + Drink + Smoke 

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
Solve by deleting conflict lines.
> Cannot open profile GNB

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
- NewDawn/NewDawn/Utils/ImageUtil.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
Photo uploads reordering logic
Alert when photo does not meet criterion
Video in slack.
> [Edit Profile] Photo upload constraints and UI

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ImageCollectionViewCell.xib
- NewDawn/NewDawn/ViewControllers/QuestionAnswerViewControllers/QuestionViewController.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Education.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Location.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_WorkJob.swift
> [image fill] Change all images view from scale fill to aspect fill + Adjust some requireness and constraint of registration

- NewDawn/NewDawn/Utils/ImageUtil.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
> [Setting] Instantly load image from local

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Models/QuestionAnswer.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/ViewControllers/QuestionAnswerViewControllers/QuestionViewController.swift
- NewDawn/NewDawn/ViewControllers/QuestionAnswerViewControllers/SelectQuestionViewController.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_DraftFinal.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Drink.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Education.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Location.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Smoke.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
Make constants shared across Registration & Edit Profiles
> [easy] Unify Constants

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Drink.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Smoke.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
Height constraints
Instantly read age after uploaded
Naming for drink and smoke
> [Edit Profile] Names and instant age

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
- NewDawn/NewDawn/Models/UserModels.swift
- NewDawn/NewDawn/Utils/LocalStorageUtil.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- Parse and save birthday and gender
- check images folder after delete app
Video in slack
> [Edit Profile] Reserve info after delete app

- NewDawn/NewDawn/ViewControllers/ViewController.swift
verify by open the simulator
the first profile becomes Teddy's (since Janice was in PENDING status)
> [easy] Hide user profile with pending review status 

- NewDawn/NewDawn/Info.plist
> [Easy] Display name

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageImTakenViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewController.swift
> [taken] lock main page when I'm taken

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Location.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
Default New York selection for picker.
Text fix for images and image picking.
> [Fix] Picker default selection

- NewDawn/NewDawn.xcodeproj/project.pbxproj
- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatPageViewController.swift
1. Move UserProfile loading to viewWillAppear and pass it into table view model
2. If I'm taken and the end user is == takenBy, re-enable the cell
> [Chat] Chat Page Optimization + fix all cell disabled bug

- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
Do not overwrite local information whenever switches to setting page.
Set local as source of truth and keep it consistent with server.
It can avoid a lot of issues caused by frequent IO and internet download.
Video in slack.
> [Edit Profile] change edit profile logic

- NewDawn/NewDawn/Base.lproj/Main.storyboard
> [easy] Adjust phone verification UI

- NewDawn/NewDawn/Base.lproj/ProfileGNB.storyboard
- NewDawn/NewDawn/Base.lproj/QuestionAnswer.storyboard
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_DraftFinal.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_Notificatioin.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
> [Registration] Back buttons for question and notification

- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
Shorten duration of long press for photo.
> [Easy] Shorter duration press

- NewDawn/NewDawn/ViewControllers/ChatPageViewControllers/ChatRoomViewController.swift
Load everything in dispatch groups and wait for profile images to be ready before reloading the view. By doing this, we don't need to download profile image for each cell anymore. And this can get rid of order mess up.
> [Chat] Prepare user profiles and profile images before reload the view to get the order right

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneAuthenticateViewController.swift
- NewDawn/NewDawn/ViewControllers/LoginViewControllers/PhoneVerifyViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageTabBarViewController.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_DraftFinal.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileSubViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/SettingPageViewController.swift
- NewDawn/NewDawn/ViewControllers/ViewController.swift
- Handle failed session tasks
- Fix local age
> [Edit Profile] Handle failed session task

- NewDawn/NewDawn/CustomLayouts/ProfileImageUploadModel.swift
- NewDawn/NewDawn/ViewControllers/RegistrationViewControllers/Profile_PhotosUpload.swift
- NewDawn/NewDawn/ViewControllers/SettingPageViewControllers/EditProfileViewController.swift
- NewDawn/NewDawn/ViewControllers/ViewController.swift
Allow image preview for filled image.
Video in Slack.
> [Image] Image preview

- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageEndViewController.swift
- NewDawn/NewDawn/ViewControllers/MainPageViewControllers/MainPageViewController.swift
> [main page] Make tab bubble counter + 1 

- NewDawn/NewDawn/ViewControllers/AppLandingViewController.swift
So we can unhide the login button successfully when we know the user has not login yet
> [Landing] Move Landing view loading logic to willAppear

- NewDawn/NewDawn/Base.lproj/MainPage.storyboard
> [Setting] A bucket of constraints
